// <auto-generated />
using System;
using Gym.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230829173118_SeedWorkoutDetailsTable")]
    partial class SeedWorkoutDetailsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym.Models.WorkoutDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Muscle = "Back",
                            Name = "Deadlift",
                            Reps = "12/10/8",
                            Sets = 3,
                            Weight = "60/70/80",
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 2,
                            Muscle = "Chest",
                            Name = "Chest Press",
                            Reps = "12/10/8/6",
                            Sets = 4,
                            Weight = "60/70/80/90",
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            Muscle = "Legs",
                            Name = "Squads",
                            Reps = "12/10/8",
                            Sets = 3,
                            Weight = "60/70/80",
                            WorkoutPlanId = 3
                        });
                });

            modelBuilder.Entity("Gym.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Today im david goggins"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Today im still david goggins"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Today im the DAVID GOGGINGS"
                        });
                });

            modelBuilder.Entity("Gym.Models.WorkoutDetails", b =>
                {
                    b.HasOne("Gym.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Details")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Gym.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
